aws_region                  = "us-east-1"
stack                       = "terraform-workshop"
fargate-task-service-role   = "terraform-workshop-task-role"
fargate-task-execution-role = "terraform-workshop-execution-role"
aws_ecr                     = "petclinic"
aws_profile                 = "default"
github_repo                 = "app-petclinic"
image_repo_name             = "petclinic"